### ISSUE TITLE
Feature Request:  save & restore

### ISSUE THREAD

**Issue by azadian** [char101/tabgroupsmenu#47]
I love this add-on, but it has already happened to me a couple times that all my groups and tabs suddenly disappeared, and it was devastating.  It desperately needs a way to save the current groups and tabs, and restore them.  Ideally I could also export them to another machine.

**Comment by char101** [comment]
There is already a popular addon for that

https://addons.mozilla.org/en-us/firefox/addon/session-manager/

Tab groups are part of firefox session data.

**Comment by azadian** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

OK, thanks for the tip.  Feel free to remove my suggestion.

NHA
- --
Norman H. Azadian   Taegerishalde 13   CH-3110 Muensingen   Switzerland
norman@azadian.ch     tel: +41 31 721 7855      mobile: +41 77 204 1981

On 04/29/2015 02:49 AM, Charles wrote:
> There is already a popular addon for that
> 
> https://addons.mozilla.org/en-us/firefox/addon/session-manager/
> 
> Tab groups are part of firefox session data.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/char101/tabgroupsmenu/issues/47#issuecomment-97274368>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJVQJw5AAoJELy8RB5leKNWlVoH/jdtxTbWr5DIXlfvdaIQ3+Q5
IlIY/zGufnBOjlny7GyGRgLbm7T+filF5MSGPhh/qX8krNWXeIZnk/oZr4Njoipv
X4k1NDlq1o2gqiVkNownuCbQLWyR3X6VcU8GG/MxMgSe3dCORzynajAjr/rzOX4m
Qdsbk9jXmY5zBUslZcSRagojHocFa1S6djHQvfx+rOreAmG8YaubMkKtzKqKa7yj
q/ULmMSvsfHgSdf8odVVontNmRvr/GGRtp/5z4vXCjl6T2ccA28AZren3NKuF3DP
055n/9NY/nz4yLugR5M4AH1b0TiP4Bv9WepeSlLlyncmSa2BZUYcKw95+zDc5is=
=AwJ6
-----END PGP SIGNATURE-----

**Comment by Spitfire1900** [comment]
close?
