### ISSUE TITLE
'Background' groups disappeared in Firefox 37.0.2

### ISSUE THREAD

**Issue by SandJ** [char101/tabgroupsmenu#48]
Having just updated Firefox to 37.0.2, my tabs for the current group re-appeared but all the other groups have disappeared.

**Comment by SandJ** [comment]
If I do "Bookmark Current Tab Set…" then it creates a tab set with my 600 or so tabs in from the 30 or so tab groups  So they are there somewhere.  But there is no Tabs Group Menu displayed, "Move to Group" only offers "New Group" and Ctrl-Shift-E / the tab groups button are ignored.

**Comment by SandJ** [comment]
I keep try different permutations of add-ons and sometimes it's OK and sometimes it is not.  It comes down to whether I get

"A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: chrome://browser/content/tabview.js:54"

when Firefox starts.  I have tried turning off all add-ons except Tab Groups Menu, then turning on add-ons one at a time and it is the appearance of the above message when Firefox starts that is the common factor, rather than a particular add-on.

**Comment by SandJ** [comment]
Now, with only this add-on enabled, Firefox started with:

A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: chrome://browser/content/tabview.js:5658

and again, no groups.

**Comment by SandJ** [comment]
I have all add-ons disabled except this one. I have had to change
dom.max_script_run_time
and
dom.max_chrome_script_run_time
to 300 to stop the script errors.  And still, there are no 'background' groups.

**Comment by SandJ** [comment]
With all add-ons disabled, Ctrl-Shift-E / and the tab icon work.  With this add-on enabled, it does not.

**Comment by char101** [comment]
Sorry but I don't use this addon anymore. Now I use https://github.com/char101/tabgroupsbtn

**Comment by SandJ** [comment]
It might be a good idea to say that on the description of this add-on, and redirecting them to your new add-on.  I would not have spent a couple of hours struggling with it if I had known.
