### ISSUE TITLE
Incompatible with Tab-Groups release 2.x

### ISSUE THREAD

**Issue by Spitfire1900** [char101/tabgroupsmenu#52]
The add-on is no longer compatible with the newest release of [Tab-Groups](https://github.com/Quicksaver/Tab-Groups).

**Comment by char101** [comment]
Works for me

![firefox](https://cloud.githubusercontent.com/assets/71255/15765666/9453c0a8-2961-11e6-9389-6808c882d8a9.png)

**Comment by Spitfire1900** [comment]
It's when you right-click a tab in Tab-Groups new quick access panel, a right click menu no longer appears.

**Comment by char101** [comment]
The context menu should work in the latest release.

**Comment by Spitfire1900** [comment]
Here you can see that it works in Tab Groups old view:![right clink old view](https://cloud.githubusercontent.com/assets/6462596/15857083/70448ebc-2c87-11e6-8ee9-8feb9a93dd71.png)

It's when right clicking tabs in Tab Groups ![new views](https://addons.cdn.mozilla.net/user-media/previews/full/174/174741.png?modified=1464726991) where right click appears to no longer work. This includes when you click the right arrow to go to individual tabs and right click a tab.

**Comment by Spitfire1900** [comment]
Closed with more granular issues #53, #54, and #55.
