### ISSUE TITLE
Unable to open more than 3 tabgroups

### ISSUE THREAD

**Issue by adrienne0914** [char101/tabgroupsmenu#56]
When I open the 4th tabgroup, it renames one of the other three with the new name. All of the tabs in the renamed group disappear leaving me with just a new tab. If I delete the new tabgroup, the renamed tabgroup and all the tabs come back.

I've been using this add-on for years.  This just started maybe a month ago.

**Comment by char101** [comment]
I think it's because this addon is not compatible with Tab Groups addon version 2.x. For now you can either use Tab Groups addon version 1.x or use another another addon that works with the 2.x version.

**Comment by adrienne0914** [comment]
Thanks for the reply. How do I go back to Tab Groups version 1.x?

**Comment by char101** [comment]
In firefox, disable **Update Add-ons automatically** from the `about:addons` page.

Then you can downgrade to Tab Groups 1.x from here

https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/versions/?page=1#version-1.0.2

I'm still using that version myself.

**Comment by adrienne0914** [comment]
Fantastic! Problem solved. I appreciate it!
